### ISSUE TITLE
How to Op someone

### ISSUE THREAD

**Issue by McOfficialPlayYT** [games647/UniversalProxy#2]
I've built and run the server but when I join and do /auth I cant because I don't have permission.
Also through the console I cant run the command "op" it says command not found.
How do I give myself perms? Please help.

**Comment by TuxCoding** [comment]
Then I guess #1 is fixed? BungeeCord doesn't have op permissions. It only has permissions groups. You can find the admin group in the config.yml of your BungeeCord server.

**Comment by McOfficialPlayYT** [comment]
so whats the /auth perm

**Comment by TuxCoding** [comment]
https://github.com/games647/UniversalProxy/blob/3b2a36d995dbf66db26b50fdddf51f74bd0bb5f9/module/cmd-auth/src/main/java/net/md_5/bungee/module/cmd/auth/CommandAuth.java#L17

`bungeecord.command.auth`

**Comment by McOfficialPlayYT** [comment]
Ok

**Comment by McOfficialPlayYT** [comment]
The server is also letting me join on my host machine but not on any other

**Comment by TuxCoding** [comment]
What error message do you got? Maybe Mojang fixed it.
